FROM node:20


WORKDIR /src/app

# for the container on the ec2 server
RUN apt-get update && apt-get install -y openssl

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps

COPY packages ./packages

RUN npm install

RUN cd packages/db && npx prisma generate && cd ../..

RUN npm run build

CMD [ "npm", "run","start-user-app" ]