name: Build and Deploy to Docker Hub

on:
    push:
        branches:
            - master


jobs: 
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v3
            
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./docker/Dockerfile.userApp
                push: true
                tags: vatsalcodes44/mypaytm:latest

            - name: Verify pushed image
              run: docker pull vatsalcodes44/mypaytm:latest

            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with: 
                host: ${{secrets.SSH_HOST}}
                username: ${{secrets.SSH_USERNAME}}
                key: ${{secrets.SSH_KEY}}
                script: |
                    sudo docker pull vatsalcodes44/mypaytm:latest
                    sudo docker stop mypaytm || true
                    sudo docker rm mypaytm || true
                    sudo docker run -d --name mypaytm --network paytm -e ${{secrets.DATABASE_URL}} -p 3005:3000 vatsalcodes44/mypaytm:latest
                  # add environment variable in docker -e ${{secrets.DATABASE_URL}
                  # add a flag so that it restarts itself
                  # try to deploy it to elastic bean stalk, using it out application will autoscale